# Generated by Django 5.1 on 2024-08-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_rename_banners_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="img",
            field=models.ImageField(null=True, upload_to="services/"),
        ),
        migrations.AddField(
            model_name="service",
            name="img_alt",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
