# Generated by Django 5.1 on 2024-08-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_service_img_service_img_alt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("detail", models.TextField()),
            ],
        ),
    ]
