# Generated by Django 5.1 on 2024-08-20 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_pages"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pages",
            new_name="Page",
        ),
    ]
