# Generated by Django 5.1 on 2024-08-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.TextField()),
                ("email", models.TextField()),
                ("detail", models.TextField()),
                ("send_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
