# Generated by Django 5.1 on 2024-08-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_enquiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="email",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="full_name",
            field=models.CharField(max_length=20),
        ),
    ]
