# Generated by Django 5.1 on 2024-08-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_enquiry_email_alter_enquiry_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="email",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="full_name",
            field=models.CharField(max_length=50),
        ),
    ]
