# Generated by Django 5.1 on 2024-08-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_alter_enquiry_email_alter_enquiry_full_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alt_text", models.CharField(max_length=150)),
                ("img", models.ImageField(null=True, upload_to="gallery_images/")),
            ],
        ),
    ]
