# Generated by Django 5.1 on 2024-08-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_gallery"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alt_text", models.CharField(max_length=150)),
                ("img", models.ImageField(null=True, upload_to="gallery_images/")),
            ],
        ),
        migrations.RenameField(
            model_name="gallery",
            old_name="alt_text",
            new_name="title",
        ),
        migrations.AddField(
            model_name="gallery",
            name="detail",
            field=models.TextField(default="Default"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gallery",
            name="img",
            field=models.ImageField(null=True, upload_to="gallery/"),
        ),
    ]
