# Generated by Django 5.1 on 2024-08-20 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_galleryimage_rename_alt_text_gallery_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="gallery",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.gallery",
            ),
        ),
    ]
