# Generated by Django 5.1 on 2024-08-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_subplan_subscriptionfeature"),
    ]

    operations = [
        migrations.AddField(
            model_name="subplan",
            name="highlight_status",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
