# Generated by Django 5.1 on 2024-08-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_subplan_highlight_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionfeature",
            name="subplan",
        ),
        migrations.AddField(
            model_name="subscriptionfeature",
            name="subplan",
            field=models.ManyToManyField(to="main.subplan"),
        ),
    ]
