# Generated by Django 5.1 on 2024-08-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_remove_subscriptionfeature_subplan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subplan",
            name="max_member",
            field=models.IntegerField(null=True),
        ),
    ]
